add solution for counter button
js-tasks-ru/vue-20210511_alexander35 pull request #2
Opened 2021-06-02 07:04 UTC by DeadTroy

2021-06-02 07:05 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-02 07:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-03 21:57 UTC, ShGKme requested changes
Требуется избавиться от вызова методов в шаблоне в 01-basics/02-MarkedList.

Для этого можно создать вычисляемое свойство, которое сразу на основе исходного списка и текущего значения фильтрации вычисляет такой список почт, который можно вывести с маркировкой. Например, список объектов с почтой и флагом о наличии маркера.

2021-06-03 21:57 UTC, ShGKme commented on 01-basics/02-MarkedList/index.html
>    </ul>
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - булево значение, которое обозначает, что класс требуется добавить.
https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax

2021-06-03 21:57 UTC, ShGKme commented on 01-basics/02-MarkedList/index.html
>    </ul>
Лучше избегать  вызова функций в шаблоне.

В этой ситуации вызов методов не создаст проблем с производительностью. Но:
1. Требуется чуть больше думать, смотря на шаблон, чтобы понять, что этот метод  не имеет побочных эффектов и работает быстро. Например, если бы это приложение было больше, чем из просто списка email-ов и фильтра, то Vue бы перезапускал вычисление этого цикла при каждом ререндеринге, каждый раз заново проверяя каждую почту. Не критично, но и не оптимально.
2. Шаблон получается менее декларативным, так как уже не декларирует значение атрибута/содержимого, а вычисляет в процессе работы.

Чтобы лучше разобраться с концепцией шаблона и вычисляемых свойств предлагается избавиться от вычисления маркировки в шаблоне и сделать для этого вычисляемое свойство.

2021-06-08 13:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-08 16:58 UTC, ShGKme reviewed
Задача 03-MeetupTitle принята.

2021-06-08 16:58 UTC, ShGKme commented on 01-basics/03-MeetupTitle/script.js
> +		}
Проверка `val != old` - не нужна. Vue не будет обрабатывать изменение, если установлено то же значение, что уже было установлено.

2021-06-11 11:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 17:11 UTC, ShGKme requested changes
Надеюсь, эта задача ещё не надоела :)
Требуется ещё немного поправить MarkedList, чтобы до конца разобраться в вычисляемых свойствах и их применении. 
Если мои комментарии кажутся спорными, или плохо понятно, почему лучше делать иначе - пишите.

2021-06-11 17:11 UTC, ShGKme commented on 01-basics/02-MarkedList/script.js
> +});
Лучше, но сейчас фактически "вручную" реализовано вычисляемое свойство.

Метод `updateEmails` обновляет исходный массив `emails` при изменении значения поиска.

В этом решении будет сложно добавить возможность изменять список `emails`, например, получать его их входного параметра, добавлять, удалять, изменять emal-ы, так как данные жёстко связаны с маркировкой.

Вместо этого лучше сделать вычисляемое свойство, которое на основе исходного списка `emails` (массива строк) и значения поиска вычислит и вернёт новый массив, но уже массив объектов, как вы сделали вручную.

Это можно сделать вручную (for + push в новый массив) или используя метод массива `map`.

2021-06-14 14:00 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-14 18:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-14 18:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-14 19:22 UTC, ShGKme requested changes
В MeetupDescription требуется избавиться от XSS, остальные задачи приняты

2021-06-14 19:22 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
`counter` в состоянии компонента - не нужен. Он никак не используется, кроме как переменная в одном месте для увеличения значения. Чтобы отправить значение на один больше, не требуется дополнительная переменная и совсем не нужно состояние компоненту. Достаточно передать значение на 1 больше: `this.$emit('increment', this.count + 1);`

2021-06-14 19:22 UTC, ShGKme commented on 02-components/02-MeetupDescription/MeetupDescription.js
> +  template: '<p class="meetup-description" v-html="description"></p>',
`v-html` выведет значение как html без какого-либо экранирования. Это потенциальный [XSS](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2%D1%8B%D0%B9_%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B8%D0%BD%D0%B3).

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С `v-html` получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

2021-06-16 09:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-16 11:03 UTC, ShGKme requested changes
В 02-components/01-CounterButtonComponent требуется избавиться от ненужной мутации входного параметра компонента. Для отправки значения на 1 больше текущего не требуется изменять текущее, достаточно отправить результат вычисления.

2021-06-16 11:03 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +      this.$emit('increment', ++this.count);
Оператор `++` изменяет значение операнда. Здесь получается изменение `count` - изменение входного параметра.

2021-06-17 06:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-17 06:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-17 06:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-17 12:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-17 14:30 UTC, ShGKme approved these changes
Принято 👍

2021-06-17 14:30 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +			return this.date.toLocaleDateString('en-EN', {
Вместо фиксированного `en-EN` лучше использовать локализацию пользователя: `navigator.language`

2021-06-17 14:32 UTC, merged